name: build

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
    name: Build with JDK ${{matrix.java}}

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-java@v4
        name: Setup JDK ${{matrix.java}}
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven build
        run: mvn -B -Plegacy verify

      ## Save the context information for use in Sonar analysis
      - name: Save Build Context
        if: ${{ matrix.java == '21' }}
        run: echo "$GITHUB_CONTEXT" > target/build-context.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      ## Attach the target directory for use in Sonar analysis
      - name: Attach Build Output
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/

  javadoc:
    runs-on: ubuntu-latest
    name: Verify JavaDocs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-repository-${{ hashFiles('**/pom.xml') }}

      - name: Generate JavaDocs
        run: mvn -B verify javadoc:javadoc -DskipTests
